/**
 * SvelteKit Vite plugin for Cinacoin.
 *
 * Automatically injects the Cinacoin provider into the SvelteKit app
 * and provides SSR-safe initialization guards.
 *
 * Usage in `vite.config.ts` (or `svelte.config.js` via `kit.vitePlugin`):
 *
 * ```ts
 * import { cinaConnectKit } from '@cinacoin/svelte/kit';
 *
 * export default defineConfig({
 *   plugins: [
 *     sveltekit(),
 *     cinaConnectKit({
 *       projectId: process.env.CINACOIN_PROJECT_ID,
 *       autoInject: true,
 *     }),
 *   ],
 * });
 * ```
 *
 * @packageDocumentation
 */

// Minimal Vite type declarations — avoids requiring vite as a compile-time dep.
// The plugin works at runtime with any Vite 5+ or 6+ installation.
interface VitePlugin {
  name: string;
  enforce?: 'pre' | 'post';
  configResolved?: (config: ResolvedConfig) => void;
  resolveId?: (id: string) => string | null | undefined;
  load?: (id: string) => string | null | undefined;
  transform?: (
    code: string,
    id: string,
  ) => { code: string; map: null } | null | undefined;
  configureServer?: (server: ViteDevServer) => void;
}

interface ResolvedConfig {
  root: string;
  plugins: VitePlugin[];
}

interface ViteDevServer {
  watcher: {
    on: (event: string, handler: () => void) => void;
  };
  moduleGraph: {
    invalidateAll: () => void;
  };
}

// ---------------------------------------------------------------------------
// Plugin Options
// ---------------------------------------------------------------------------

/**
 * Configuration options for the Cinacoin SvelteKit Vite plugin.
 */
export interface CinacoinKitOptions {
  /**
   * Cinacoin project ID.
   *
   * When provided, the plugin generates an auto-import module with
   * pre-configured defaults.
   */
  projectId?: string;

  /**
   * Whether to automatically inject the Cinacoin provider
   * into the SvelteKit app layout.
   *
   * @default true
   */
  autoInject?: boolean;

  /**
   * The import path to the Cinacoin Svelte package.
   *
   * @default '@cinacoin/svelte'
   */
  importPath?: string;

  /**
   * The global virtual module name for auto-generated config.
   *
   * @default 'virtual:cinacoin-config'
   */
  virtualModuleName?: string;

  /**
   * Chains to enable.
   *
   * When provided, generates a chain configuration in the virtual module.
   */
  chains?: Array<{
    id: number;
    name: string;
    rpcUrl?: string;
    nativeCurrency?: {
      name: string;
      symbol: string;
      decimals: number;
    };
  }>;

  /**
   * Whether to enable SSR-safe store initialization.
   *
   * When true, the plugin wraps store accessors with SSR guards
   * to prevent `window is not defined` errors.
   *
   * @default true
   */
  ssrGuards?: boolean;

  /**
   * Whether to auto-import Cinacoin composables.
   *
   * @default true
   */
  autoImport?: boolean;
}

/**
 * Default plugin options.
 */
const DEFAULT_OPTIONS: Required<
  Omit<CinacoinKitOptions, 'chains'>
> & {
  chains: CinacoinKitOptions['chains'];
} = {
  projectId: '',
  autoInject: true,
  importPath: '@cinacoin/svelte',
  virtualModuleName: 'virtual:cinacoin-config',
  chains: undefined,
  ssrGuards: true,
  autoImport: true,
};

// ---------------------------------------------------------------------------
// Virtual Module — auto-generated config
// ---------------------------------------------------------------------------

/**
 * Generate the virtual module content for Cinacoin configuration.
 */
function generateConfigModule(options: CinacoinKitOptions): string {
  const projectId = options.projectId ?? '';
  const importPath = options.importPath ?? DEFAULT_OPTIONS.importPath;
  const chains = options.chains;

  let module = `// Auto-generated by @cinacoin/svelte/kit plugin\n`;
  module += `import { createCinacoin } from '${importPath}';\n\n`;

  module += `/** Auto-configured Cinacoin options. */\n`;
  module += `export const cinaConnectConfig = {\n`;
  module += `  projectId: '${projectId}',\n`;

  if (chains && chains.length > 0) {
    module += `  chains: ${JSON.stringify(chains)},\n`;
  }

  module += `};\n\n`;

  module += `/** Create a pre-configured Cinacoin instance. */\n`;
  module += `export function createConfiguredCinacoin() {\n`;
  module += `  return createCinacoin(cinaConnectConfig);\n`;
  module += `}\n`;

  return module;
}

/**
 * Generate the SSR-safe store wrapper module.
 */
function generateSsrGuardsModule(importPath: string): string {
  return `// Auto-generated SSR-safe store wrappers by @cinacoin/svelte/kit plugin
import { writable, readable, type Readable, type Writable } from 'svelte/store';

/** Check if running in browser environment. */
function isBrowser(): boolean {
  return typeof window !== 'undefined';
}

/**
 * SSR-safe writable store creator.
 *
 * During SSR, the store is initialized with the fallback value.
 * On hydration, it reads from the provided getter.
 */
export function ssrWritable<T>(
  getValue: () => T,
  fallback: T,
): Writable<T> {
  const initialValue = isBrowser() ? getValue() : fallback;
  return writable(initialValue);
}

/**
 * SSR-safe readable store creator.
 */
export function ssrReadable<T>(
  getValue: () => T,
  fallback: T,
): Readable<T> {
  const initialValue = isBrowser() ? getValue() : fallback;
  return readable(initialValue);
}

/**
 * SSR-safe store value getter.
 */
export function ssrValue<T>(
  getValue: () => T,
  fallback: T,
): T {
  if (!isBrowser()) return fallback;
  try {
    return getValue();
  } catch {
    return fallback;
  }
}

// Re-export core stores from Cinacoin
export {
  isConnected,
  address,
  balance,
  chainId,
  status,
  error,
  isConnecting,
  hasError,
  chains,
  initCinacoin,
  getConnector,
  open,
  close,
  switchChain,
  resetCinacoin,
  createCinacoin,
  walletCapabilities,
  capabilitiesLoading,
  capabilitiesError,
  fetchWalletCapabilities,
  has,
  getChainCaps,
  filterBy,
  sendCalls,
  atomicBatch,
  callsStatus,
  allSucceeded,
  failedReceipts,
} from '${importPath}';
`;
}

// ---------------------------------------------------------------------------
// Vite Plugin
// ---------------------------------------------------------------------------

/**
 * SvelteKit Vite plugin for Cinacoin integration.
 *
 * Features:
 * - Auto-generates a virtual config module (`virtual:cinacoin-config`)
 * - Provides SSR-safe store wrappers via `virtual:cinacoin-ssr-guards`
 * - Optionally auto-injects provider into SvelteKit layouts
 *
 * @param options - Plugin configuration options.
 * @returns Vite Plugin instance.
 */
export function cinaConnectKit(
  options: CinacoinKitOptions = {},
): VitePlugin {
  const opts: Required<Omit<CinacoinKitOptions, 'chains'>> & {
    chains: CinacoinKitOptions['chains'];
  } = {
    ...DEFAULT_OPTIONS,
    ...options,
  };

  const virtualModuleId = opts.virtualModuleName!;
  const resolvedVirtualModuleId = '\x00' + virtualModuleId;

  const ssrGuardsModuleId = 'virtual:cinacoin-ssr-guards';
  const resolvedSsrGuardsModuleId = '\x00' + ssrGuardsModuleId;

  // Capture for transform closure
  const _ssrModuleRef = ssrGuardsModuleId;

  return {
    name: 'cinacoin-sveltekit',
    enforce: 'pre',

    configResolved(config: ResolvedConfig) {
      // Config resolved — virtual modules are now available
      void config;
    },

    resolveId(id: string) {
      if (id === virtualModuleId) {
        return resolvedVirtualModuleId;
      }
      if (id === ssrGuardsModuleId) {
        return resolvedSsrGuardsModuleId;
      }
      return null;
    },

    load(id: string) {
      if (id === resolvedVirtualModuleId) {
        return generateConfigModule(opts);
      }
      if (id === resolvedSsrGuardsModuleId) {
        return generateSsrGuardsModule(opts.importPath!);
      }
      return null;
    },

    // Transform Svelte files to add SSR guard hints when enabled
    transform(code: string, id: string) {
      if (!opts.ssrGuards) return null;
      if (!id.endsWith('.svelte') && !id.endsWith('.ts')) return null;

      if (
        id.endsWith('.svelte') &&
        code.includes("from 'svelte/store'") &&
        !code.includes('ssrValue') &&
        !code.includes('ssrWritable')
      ) {
        return {
          code: `// SSR guards enabled — use import { ssrWritable, ssrValue } from '${_ssrModuleRef}'\n${code}`,
          map: null,
        };
      }

      return null;
    },

    configureServer(server: ViteDevServer) {
      server.watcher.on('change', () => {
        server.moduleGraph.invalidateAll();
      });
    },
  };
}

/**
 * Alias for cinaConnectKit — the SvelteKit integration plugin.
 *
 * @deprecated Use `cinaConnectKit` instead.
 */
export const sveltekitPlugin = cinaConnectKit;
