apiVersion: v1
kind: Service
metadata:
  name: erigon-ethereum
  namespace: cinacoin
  labels:
    app: erigon-ethereum
    chain: ethereum
    component: blockchain-node
spec:
  type: ClusterIP
  ports:
    - name: rpc
      port: 8545
      targetPort: rpc
      protocol: TCP
    - name: ws
      port: 8546
      targetPort: ws
      protocol: TCP
    - name: metrics
      port: 6060
      targetPort: metrics
      protocol: TCP
    - name: p2p
      port: 30303
      targetPort: p2p
      protocol: TCP
  selector:
    app: erigon-ethereum
