{{- if .Values.rpcProxy.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rpc-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app: rpc-proxy
    {{- include "cinacoin.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rpc-proxy
  minReplicas: {{ .Values.rpcProxy.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.rpcProxy.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.rpcProxy.autoscaling.targetCPUUtilization }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.rpcProxy.autoscaling.targetCPUUtilization }}
    {{- end }}
    {{- if .Values.rpcProxy.autoscaling.targetMemoryUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.rpcProxy.autoscaling.targetMemoryUtilization }}
    {{- end }}
{{- end }}
