#!/usr/bin/env node
/**
 * Build script for @cinacoin/design-tokens
 *
 * 1. Reads token JSON files.
 * 2. Generates a combined CSS file under dist/css/variables.css.
 * 3. Generates a JS module under dist/ that re-exports tokens.
 *
 * Run:  npx tsx scripts/build.ts
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const distDir = join(root, 'dist');
const cssDir = join(distDir, 'css');
// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
function readJson(path) {
    return JSON.parse(readFileSync(path, 'utf-8'));
}
function flattenTheme(theme) {
    const flat = {};
    const groups = ['colors', 'radii', 'shadows', 'typography', 'spacing', 'animations', 'zIndex'];
    for (const g of groups) {
        const obj = theme[g] ?? {};
        for (const [key, value] of Object.entries(obj)) {
            flat[key] = String(value);
        }
    }
    return flat;
}
function toCssBlock(selector, map) {
    const body = Object.entries(map)
        .map(([k, v]) => `  ${k}: ${v};`)
        .join('\n');
    return `${selector} {\n${body}\n}`;
}
// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
function build() {
    // Ensure output dirs exist
    for (const dir of [distDir, cssDir]) {
        if (!existsSync(dir))
            mkdirSync(dir, { recursive: true });
    }
    // Load themes
    const defaultTheme = readJson(join(root, 'tokens/themes/default.json'));
    const lightTheme = readJson(join(root, 'tokens/themes/light.json'));
    const minimalTheme = readJson(join(root, 'tokens/themes/minimal.json'));
    const defaultMap = flattenTheme(defaultTheme.theme);
    const lightMap = flattenTheme(lightTheme.theme);
    const minimalMap = flattenTheme(minimalTheme.theme);
    // Generate combined CSS
    const cssContent = [
        '/**',
        ' * Cinacoin Design Tokens — Generated CSS Variables',
        ' * Do not edit this file directly. Run `npm run build` in design-tokens.',
        ' */',
        '',
        toCssBlock(':root', defaultMap),
        '',
        toCssBlock('.ocx-theme-light', lightMap),
        '',
        toCssBlock('.ocx-theme-minimal', minimalMap),
        '',
    ].join('\n');
    writeFileSync(join(cssDir, 'variables.css'), cssContent, 'utf-8');
    // Generate index.js re-export (for consumers not using ESM)
    const indexContent = `// Auto-generated by scripts/build.ts — do not edit manually
export { cssVariables, cssVariablesLight, cssVariablesMinimal, themes, tokens, global, semantic, components } from '../src/index.js';
`;
    writeFileSync(join(distDir, 'index.js'), indexContent, 'utf-8');
    console.log('✅  design-tokens build complete');
    console.log(`   → ${join(cssDir, 'variables.css')}`);
    console.log(`   → ${join(distDir, 'index.js')}`);
}
build();
//# sourceMappingURL=build.js.map