apiVersion: v1
kind: Service
metadata:
  name: push-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: push-server
    component: push
    {{- include "cinacoin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pushServer.service.type }}
  ports:
    - name: http
      port: {{ .Values.pushServer.service.port }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.pushServer.ports.metrics }}
      targetPort: metrics
      protocol: TCP
  selector:
    app: push-server
