{{- if eq .Release.Namespace "default" -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace | default "cinaconnect" }}
  labels:
    name: {{ .Release.Namespace | default "cinaconnect" }}
    managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: cinaconnect
{{- end }}
