name = "cinacoin-rpc-proxy"
main = "worker.ts"
compatibility_date = "2024-01-01"
account_id = "7ea8e46d8210bad342fa7595f7935fea"

routes = [
  { pattern = "rpc.cinacoin.com/*", zone_name = "cinacoin.com" }
]

[vars]
CACHE_TTL = "300"
LOG_LEVEL = "info"
MAX_RETRIES = "3"
REQUEST_TIMEOUT_MS = "30000"

[[kv_namespaces]]
binding = "RPC_CACHE"
id = "f91dde2603b44c2f830d42330be9778a"
