apiVersion: v1
kind: Service
metadata:
  name: nats-cluster
  namespace: {{ .Release.Namespace }}
  labels:
    app: nats
    component: messaging
    {{- include "cinacoin.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: client
      port: {{ .Values.nats.ports.client }}
      targetPort: client
      protocol: TCP
    - name: cluster
      port: {{ .Values.nats.ports.cluster }}
      targetPort: cluster
      protocol: TCP
    - name: monitor
      port: {{ .Values.nats.ports.monitor }}
      targetPort: monitor
      protocol: TCP
  selector:
    app: nats
---
apiVersion: v1
kind: Service
metadata:
  name: nats-headless
  namespace: {{ .Release.Namespace }}
  labels:
    app: nats
    component: messaging
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: client
      port: {{ .Values.nats.ports.client }}
      targetPort: client
      protocol: TCP
    - name: cluster
      port: {{ .Values.nats.ports.cluster }}
      targetPort: cluster
      protocol: TCP
  selector:
    app: nats
