apiVersion: v1
kind: Service
metadata:
  name: relay-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: relay-server
    component: core
    {{- include "cinacoin.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.relay.ports.metrics }}"
spec:
  type: {{ .Values.relay.service.type }}
  ports:
    - name: ws
      port: {{ .Values.relay.service.port }}
      targetPort: ws
      protocol: TCP
    - name: http
      port: {{ .Values.relay.ports.http }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.relay.ports.metrics }}
      targetPort: metrics
      protocol: TCP
  selector:
    app: relay-server
