name = "cinacoin-keys-server"
main = "worker.ts"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "keys.cinacoin.com/*", zone_name = "cinacoin.com" }
]

[vars]
LOG_LEVEL = "info"
SESSION_TTL = "86400"
MAX_KEYS_PER_USER = "100"

[[d1_databases]]
binding = "DB"
database_name = "cinacoin-keys"
database_id = "67d98935-9d34-4e3d-b357-af745fa47596"

[[kv_namespaces]]
binding = "SESSIONS"
id = "b60edcfb4052452780701cbf7a06aeb9"
