import { jsx as _jsx } from "react/jsx-runtime";
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};
export default function RootLayout({ children, }) {
    return (_jsx("html", { lang: "en", children: _jsx("body", { children: children }) }));
}
//# sourceMappingURL=layout.js.map